/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */


export interface paths {
  "/outages": {
    /**
     * Returns all outages in our system. 
     * @description An outage is when a device can no longer provide service and is declared as offline. Each outage consists of a device ID, begin time, and end time.
     */
    get: {
      /**
       * Returns all outages in our system. 
       * @description An outage is when a device can no longer provide service and is declared as offline. Each outage consists of a device ID, begin time, and end time.
       */
      responses: {
        200: components["responses"]["Outages"];
        403: components["responses"]["403"];
        429: components["responses"]["429"];
      };
    };
  };
  "/site-info/{siteId}": {
    /**
     * Returns information about a specific site. 
     * @description The site information contains the ID and name of the site. It also contains a list of devices that make up the site.
     */
    get: {
      /**
       * Returns information about a specific site. 
       * @description The site information contains the ID and name of the site. It also contains a list of devices that make up the site.
       */
      responses: {
        200: components["responses"]["SiteInfo"];
        403: components["responses"]["403"];
        404: components["responses"]["404"];
        429: components["responses"]["429"];
      };
    };
  };
  "/site-outages/{siteId}": {
    /**
     * Posts outages for a specific site with enhanced information. 
     * @description The outages posted should contain a device ID, device name, begin time, and end time.
     */
    post: {
      /**
       * Posts outages for a specific site with enhanced information. 
       * @description The outages posted should contain a device ID, device name, begin time, and end time.
       */
      requestBody?: {
        content: {
          "application/json": components["schemas"]["EnhancedOutages"];
        };
      };
      responses: {
        200: components["responses"]["200"];
        403: components["responses"]["403"];
        404: components["responses"]["404"];
        429: components["responses"]["429"];
      };
    };
  };
}

export type webhooks = Record<string, never>;

export interface components {
  schemas: {
    /** @description Error message returned if there is a problem */
    ErrorMessage: {
      message: string;
    };
    /** @description An array outages */
    Outages: ({
        /**
         * @description The device ID the outage pertains to 
         * @example 44c02564-a229-4f51-8ded-cc7bcb202566
         */
        id: string;
        /**
         * Format: date-time 
         * @description Outage begin date time 
         * @example 2022-01-01T00:00:00.000Z
         */
        begin: string;
        /**
         * Format: date-time 
         * @description Outage end date time 
         * @example 2022-01-02T12:01:59.123Z
         */
        end: string;
      })[];
    /**
     * @description Identifier for a site 
     * @example pear-tree
     */
    SiteId: string;
    /** @description Information on a site */
    SiteInfo: {
      /**
       * @description The ID of the site 
       * @example pear-tree
       */
      id: string;
      /**
       * @description The display name of the site 
       * @example Pear Tree
       */
      name: string;
      devices: ({
          /**
           * @description The device ID 
           * @example 44c02564-a229-4f51-8ded-cc7bcb202566
           */
          id: string;
          /**
           * @description The display name of the device 
           * @example Partridge
           */
          name: string;
        })[];
    };
    /** @description An array of outages enhanced with extra information */
    EnhancedOutages: ({
        /**
         * @description The device ID the outage pertains to 
         * @example 44c02564-a229-4f51-8ded-cc7bcb202566
         */
        id: string;
        /**
         * @description The display name of the device the outage pertains to 
         * @example Partridge
         */
        name: string;
        /**
         * Format: date-time 
         * @description Outage begin date time 
         * @example 2022-01-01T00:00:00.000Z
         */
        begin: string;
        /**
         * Format: date-time 
         * @description Outage end date time 
         * @example 2022-01-02T12:01:59.123Z
         */
        end: string;
      })[];
  };
  responses: {
    /** @description Successfully processed request. */
    200: never;
    /** @description We cannot process your request because it doesn't match the required format. */
    400: {
      content: {
        "application/json": components["schemas"]["ErrorMessage"];
      };
    };
    /** @description You do not have the required permissions to make this request. */
    403: {
      content: {
        "application/json": components["schemas"]["ErrorMessage"];
      };
    };
    /** @description You have requested a resource that does not exist. */
    404: {
      content: {
        "application/json": components["schemas"]["ErrorMessage"];
      };
    };
    /** @description You've exceeded your limit for your API key. */
    429: {
      content: {
        "application/json": components["schemas"]["ErrorMessage"];
      };
    };
    /** @description Outages response. */
    Outages: {
      content: {
        "application/json": components["schemas"]["Outages"];
      };
    };
    /** @description Site information response. */
    SiteInfo: {
      content: {
        "application/json": components["schemas"]["SiteInfo"];
      };
    };
  };
  parameters: {
    /** @description Identifier for a site */
    SiteId: components["schemas"]["SiteId"];
  };
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type external = Record<string, never>;

export type operations = Record<string, never>;
